/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Cv3AmbulanceWlList {
    }
}
declare global {
    interface HTMLCv3AmbulanceWlListElement extends Components.Cv3AmbulanceWlList, HTMLStencilElement {
    }
    var HTMLCv3AmbulanceWlListElement: {
        prototype: HTMLCv3AmbulanceWlListElement;
        new (): HTMLCv3AmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "cv3-ambulance-wl-list": HTMLCv3AmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface Cv3AmbulanceWlList {
    }
    interface IntrinsicElements {
        "cv3-ambulance-wl-list": Cv3AmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cv3-ambulance-wl-list": LocalJSX.Cv3AmbulanceWlList & JSXBase.HTMLAttributes<HTMLCv3AmbulanceWlListElement>;
        }
    }
}
